from pathlib import Path
import pandas as pd, json, matplotlib.pyplot as plt
root=Path('/home/wlk/projects/navigation-aware-resistance-hnsw');out=root/'results/icba_bn_apd';docs=root/'docs/icba_bn_apd';figs=root/'figures/icba_bn_apd';man=root/'manifests/icba_bn_apd_decision.json'
for p in [out,docs,figs,man.parent]:p.mkdir(parents=True,exist_ok=True)
decision=json.loads((out/'phase1_decision.json').read_text())['decision'];state=pd.read_csv(out/'state_conditioned_advantage.csv');portal=pd.read_csv(out/'marginal_portal_value.csv');primary=pd.read_csv(out/'marginal_primary_value.csv');dedup=pd.read_csv(out/'dedup_cost_bounds.csv')
texts={
'shared_frontier_semantics.md':'# Shared-frontier semantics\n\nNOT RUN: Phase 1 did not identify a deployable truth-free trigger. The intended bridge remains primary completion followed by a shared auxiliary queue, visited set and distance cache under one fixed budget; no implementation evidence was generated.',
'adaptive_optimization_log.md':'# Adaptive optimization log\n\nNo optimization round was opened and zero candidates were generated because the Phase 1 entry Gate failed. No parameter, portal, scheduler, threshold or data role was altered.',
'statistical_analysis.md':'# Statistical analysis\n\nHistorical selection and holdout records were treated solely as replay development instances. Named-build summaries use the three frozen builds descriptively. Positive portal value exists globally, but primary-NDC-conditioned median advantage is not positive under the preregistered rule.',
'cost_analysis.md':'# Cost analysis\n\nIndependent CALS cost is measured from frozen lane sums. Candidate-set overlap provides only a reproducible lower bound on possible sharing; complete visited traces are absent, so true shared NDC is NOT_ESTIMABLE and no deployment economics claim is made.',
'final_report.md':f'# Final report\n\nPhase 1 stopped the method route before implementation. Final decision: {decision}. Positive rescue remains a truth-defined mechanism observation, but the frozen records do not support a truth-free deployment trigger. Shared-frontier, optimization, certification and 100K pilots were not run.',
'executive_brief.md':f'# Executive brief\n\nCALS portals sometimes rescue failures efficiently, but the available deployment-visible state does not tell us when to use them. Decision: {decision}. The next scientifically valid task is instrumentation-only collection of richer truth-free search-state traces on unused development queries.'}
for n,t in texts.items():(docs/n).write_text(t+'\n')
status=pd.DataFrame([{'status':'NOT_RUN_DUE_TO_PHASE1_GATE','decision':decision}])
for n in ['mechanical_equivalence.csv','candidate_lineage.csv','operator_results.csv','pareto_frontier.csv','certification_results.csv','build_robustness.csv','cost_break_even.csv']:
 status.to_csv(out/n,index=False)
pd.DataFrame([{'gate':'PHASE1_TWO_DATASETS_POSITIVE','passed':True},{'gate':'TRUTH_FREE_STATE_ADVANTAGE','passed':False},{'gate':'SHARED_IMPLEMENTATION','passed':False},{'gate':'SMOKE_PARETO','passed':False},{'gate':'CERTIFICATION','passed':False}]).to_csv(out/'unified_gate_table.csv',index=False)
plots=[('portal_primary_value',portal,'raw_ef','median_recall_value'),('state_advantage',state,'coverage','median_advantage'),('dedup_bounds',dedup,'independent_cals_cost_mean','ideal_shared_cost_mean'),('portal_count',portal,'portal_count','mean_recall_gain'),('risk_value',portal,'raw_ef','median_risk_value'),('primary_continue',primary,'from_ef','recall_value'),('top1_state',state,'median_advantage','median_advantage_after_top1pct'),('build_state',state,'raw_ef','median_advantage'),('candidate_lower_bound',dedup,'raw_ef','candidate_dedup_fraction_mean'),('coverage',state,'raw_ef','coverage'),('truth_free_gate',state,'median_continue_value','median_portal_value'),('phase1_stop',portal,'mean_additional_ndc','mean_recall_gain')]
for i,(name,d,x,y) in enumerate(plots,1):
 fig,ax=plt.subplots(figsize=(6,4));ax.scatter(d[x],d[y],s=14,alpha=.65);ax.set_xlabel(x);ax.set_ylabel(y);ax.set_title(name.replace('_',' '));fig.tight_layout();fig.savefig(figs/f'{i:02d}_{name}.png',dpi=130);fig.savefig(figs/f'{i:02d}_{name}.pdf');plt.close(fig)
manifest={'decision_label':decision,'evidence_level':'EXPLORATORY_DEVELOPMENT','branch':'exp/icba_bn_apd_budget_reallocation','base_commit':'e129ea37915138c00280983bc4306dd9d8442e13','phase1_gate_passed':False,'entered_shared_implementation':False,'optimization_rounds':0,'candidate_count':0,'sealed_roles_accessed':False,'validation_dev_accessed':False,'formal_test_accessed':False,'certification_evaluation_future_accessed':False,'next_authorized_task':'OBSERVABLE_TRIGGER_INSTRUMENTATION_GATE_ONLY'}
man.write_text(json.dumps(manifest,indent=2))
print(decision,len(texts),len(plots))
