#include "hnswlib/hnswlib.h"
#include <algorithm>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <queue>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
using Index=hnswlib::HierarchicalNSW<float>; using Label=hnswlib::labeltype; using Internal=hnswlib::tableint;
using Item=std::pair<float,Label>; using RawItem=std::pair<float,Internal>;
struct Mat{size_t n,d;std::vector<float>x;}; struct Truth{size_t n,k;std::vector<uint32_t>x;}; struct Portal{std::string rule;Label external;Internal internal;std::string build;};
template<class T>T readv(std::ifstream&f){T v{};f.read((char*)&v,sizeof(v));if(!f)throw std::runtime_error("short binary");return v;}
Mat mat(const char*p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("query missing");Mat m{(size_t)readv<uint64_t>(f),(size_t)readv<uint64_t>(f),{}};m.x.resize(m.n*m.d);f.read((char*)m.x.data(),m.x.size()*sizeof(float));return m;}
Truth truth(const char*p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("truth missing");Truth t{(size_t)readv<uint64_t>(f),(size_t)readv<uint64_t>(f),{}};t.x.resize(t.n*t.k);f.read((char*)t.x.data(),t.x.size()*sizeof(uint32_t));return t;}
std::vector<size_t> ids(const char*p){std::ifstream f(p);if(!f)throw std::runtime_error("query id file missing");std::vector<size_t>v;std::string s;while(std::getline(f,s)){if(s.empty()||s.find("query_id")!=std::string::npos)continue;v.push_back(std::stoull(s));}return v;}
std::vector<Item> labels(const Index&idx,std::priority_queue<RawItem,std::vector<RawItem>,Index::CompareByFirst> q){std::vector<Item>v;while(!q.empty()){auto z=q.top();q.pop();v.emplace_back(z.first,idx.getExternalLabel(z.second));}std::sort(v.begin(),v.end());return v;}
std::vector<Item> native(std::priority_queue<Item>q){std::vector<Item>v;while(!q.empty()){v.push_back(q.top());q.pop();}std::sort(v.begin(),v.end());return v;}
std::string join(const std::vector<Item>&v){std::ostringstream o;for(size_t i=0;i<v.size();++i){if(i)o<<';';o<<v[i].second;}return o.str();}
std::string join_dist(const std::vector<Item>&v){std::ostringstream o;o.precision(9);for(size_t i=0;i<v.size();++i){if(i)o<<';';o<<v[i].first;}return o.str();}
uint64_t hashv(const std::vector<Item>&v){uint64_t h=1469598103934665603ULL;for(auto&a:v){h^=(uint64_t)a.second;h*=1099511628211ULL;}return h;}
size_t hits(const std::vector<Item>&v,const Truth&t,size_t q){std::set<uint32_t>s;for(size_t i=0;i<t.k;i++)s.insert(t.x[q*t.k+i]);size_t z=0;for(size_t i=0;i<std::min(t.k,v.size());i++)z+=s.count((uint32_t)v[i].second);return z;}
std::vector<Portal> portals(const char*p){std::ifstream f(p);if(!f)throw std::runtime_error("registry missing");std::vector<Portal>v;std::string line;while(std::getline(f,line)){if(line.empty()||line.rfind("portal_rule_id",0)==0)continue;std::stringstream s(line);std::string a,b,c,d;std::getline(s,a,',');std::getline(s,b,',');std::getline(s,c,',');std::getline(s,d,',');v.push_back({a,(Label)std::stoull(b),(Internal)std::stoul(c),d});}return v;}
struct Trace{std::vector<Item> full;std::vector<Item> native_topk;long ndc;};
Trace primary_trace(const Index&idx,const float*q,size_t ef,size_t k){Internal cur=idx.enterpoint_node_;float cd=idx.fstdistfunc_(q,idx.getDataByInternalId(cur),idx.dist_func_param_);long ndc=1;for(int level=idx.maxlevel_;level>0;--level){bool changed=true;while(changed){changed=false;unsigned int*d=(unsigned int*)idx.get_linklist(cur,level);int n=idx.getListCount(d);Internal*a=(Internal*)(d+1);for(int i=0;i<n;i++){float x=idx.fstdistfunc_(q,idx.getDataByInternalId(a[i]),idx.dist_func_param_);ndc++;if(x<cd){cd=x;cur=a[i];changed=true;}}}}auto before=idx.metric_distance_computations.load();auto raw=idx.searchBaseLayerST<true,true>(cur,q,ef);ndc+=idx.metric_distance_computations.load()-before;auto trimmed=raw;while(trimmed.size()>k)trimmed.pop();return {labels(idx,raw),labels(idx,trimmed),ndc};}
int main(int argc,char**argv){try{if(argc!=9){std::cerr<<"usage: cals_fixed_portal_runner INDEX QUERIES TRUTH QUERY_IDS EF_GRID REGISTRY BUILD OUTPUT\n";return 2;}Mat q=mat(argv[2]);Truth t=truth(argv[3]);auto qids=ids(argv[4]);auto preg=portals(argv[6]);hnswlib::L2Space space(q.d);Index idx(&space,argv[1],false);std::vector<size_t>efs;std::stringstream es(argv[5]);std::string s;while(std::getline(es,s,','))efs.push_back(std::stoul(s));std::ofstream out(argv[8]);out<<"query_id,build_id,raw_ef,lane_type,portal_rule_id,portal_external_label,portal_internal_tableint,candidate_labels,candidate_distances,candidate_count,topk_labels,recall_at_10,ndc,expansions,wall_clock_ns,candidate_hash,trace_hash,termination_reason,native_tracer_equal,roundtrip_ok\n";for(auto ef:efs)for(auto qi:qids){if(qi>=q.n||qi>=t.n)throw std::runtime_error("query id out of range");const float*x=q.x.data()+qi*q.d;idx.setEf(ef);auto a=std::chrono::steady_clock::now();auto nv=native(idx.searchKnn(x,t.k));auto z=primary_trace(idx,x,std::max(ef,t.k),t.k);auto b=std::chrono::steady_clock::now();auto full=z.full,tk=z.native_topk;bool eq=(tk==nv);out<<qi<<','<<argv[7]<<','<<ef<<",primary,PRIMARY,,,"<<join(full)<<','<<join_dist(full)<<','<<full.size()<<','<<join(tk)<<','<<hits(tk,t,qi)/(double)t.k<<','<<z.ndc<<','<<z.ndc<<','<<std::chrono::duration_cast<std::chrono::nanoseconds>(b-a).count()<<','<<hashv(full)<<','<<hashv(tk)<<",native_stop,"<<eq<<",1\n";for(auto&p:preg){if(idx.getExternalLabel(p.internal)!=p.external)throw std::runtime_error("portal roundtrip failed");auto before=idx.metric_distance_computations.load();auto c=std::chrono::steady_clock::now();auto av=labels(idx,idx.searchBaseLayerST<true,true>(p.internal,x,std::max(ef,t.k)));auto d=std::chrono::steady_clock::now();long ndc=idx.metric_distance_computations.load()-before;auto at=av;if(at.size()>t.k)at.resize(t.k);out<<qi<<','<<argv[7]<<','<<ef<<",auxiliary,"<<p.rule<<','<<p.external<<','<<p.internal<<','<<join(av)<<','<<join_dist(av)<<','<<av.size()<<','<<join(at)<<','<<hits(at,t,qi)/(double)t.k<<','<<ndc<<','<<ndc<<','<<std::chrono::duration_cast<std::chrono::nanoseconds>(d-c).count()<<','<<hashv(av)<<','<<hashv(at)<<",independent_lane_stop,1,1\n";}}return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
