#include "hnswlib/hnswlib.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <queue>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace {
using Index=hnswlib::HierarchicalNSW<float>; using Node=hnswlib::tableint;
using Adj=std::vector<std::vector<Node>>; using Labeled=std::vector<std::pair<float,std::uint32_t>>;
struct Matrix{std::size_t rows{},cols{};std::vector<float> x;};
struct Truth{std::size_t rows{},k{};std::vector<std::uint32_t> x;};
struct Result{Labeled labels;std::size_t ndc{},original_calls{},delta_calls{},delta_enqueued{},delta_expanded{};long long first_delta_expansion{-1};};
class Space final:public hnswlib::SpaceInterface<float>{public:Space(std::size_t d,bool ip):s_{d,ip}{}std::size_t get_data_size()override{return s_.d*sizeof(float);}hnswlib::DISTFUNC<float> get_dist_func()override{return fn;}void* get_dist_func_param()override{return&s_;}private:struct S{std::size_t d;bool ip;}s_;static float fn(const void*a0,const void*b0,const void*s0){auto*s=static_cast<const S*>(s0);auto*a=static_cast<const float*>(a0);auto*b=static_cast<const float*>(b0);float v=0;if(s->ip){for(std::size_t i=0;i<s->d;++i)v+=a[i]*b[i];return 1-v;}for(std::size_t i=0;i<s->d;++i){float z=a[i]-b[i];v+=z*z;}return v;}};
template<class T>T scalar(std::ifstream&f){T x{};f.read(reinterpret_cast<char*>(&x),sizeof(x));if(!f)throw std::runtime_error("truncated binary");return x;}
Matrix matrix(const char*p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("queries open failed");Matrix m;m.rows=scalar<std::uint64_t>(f);m.cols=scalar<std::uint64_t>(f);m.x.resize(m.rows*m.cols);f.read(reinterpret_cast<char*>(m.x.data()),m.x.size()*sizeof(float));if(!f)throw std::runtime_error("queries invalid");return m;}
Truth truth(const char*p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("truth open failed");Truth t;t.rows=scalar<std::uint64_t>(f);t.k=scalar<std::uint64_t>(f);t.x.resize(t.rows*t.k);f.read(reinterpret_cast<char*>(t.x.data()),t.x.size()*sizeof(std::uint32_t));if(!f)throw std::runtime_error("truth invalid");return t;}
std::vector<std::size_t> efs(const std::string&s){std::vector<std::size_t>v;std::stringstream x(s);std::string z;while(std::getline(x,z,','))v.push_back(std::stoul(z));return v;}
Adj edges(const char*p,std::size_t n){std::ifstream f(p);if(!f)throw std::runtime_error("edge open failed");Adj a(n);std::string l;std::getline(f,l);while(std::getline(f,l)){if(l.empty())continue;std::stringstream s(l);std::string x,y;std::getline(s,x,',');std::getline(s,y,',');auto u=std::stoul(x),v=std::stoul(y);if(u>=n||v>=n)throw std::runtime_error("edge endpoint invalid");a[u].push_back(v);}return a;}
float dist(const Index&i,const void*q,Node u){return i.fstdistfunc_(q,i.getDataByInternalId(u),i.dist_func_param_);}
std::vector<Node> upper(const Index&i,Node u,int l){auto*r=i.get_linklist_at_level(u,l);auto n=i.getListCount(r);auto*x=reinterpret_cast<const Node*>(r+1);return{x,x+n};}
Labeled ordered(std::priority_queue<std::pair<float,hnswlib::labeltype>>h){Labeled r;while(!h.empty()){r.emplace_back(h.top().first,static_cast<std::uint32_t>(h.top().second));h.pop();}std::sort(r.begin(),r.end());return r;}
std::vector<float> scales(const Index&i,const Adj&o){std::vector<float>s(o.size(),1);for(std::size_t u=0;u<o.size();++u){std::vector<float>d;for(auto v:o[u])d.push_back(dist(i,i.getDataByInternalId(u),v));if(!d.empty()){auto m=d.begin()+d.size()/2;std::nth_element(d.begin(),m,d.end());s[u]=std::max(*m,1e-12f);}}return s;}
Result search(const Index&i,const Adj&o,const Adj&delta,const std::vector<float>&scale,const void*q,std::size_t k,std::size_t ef,const std::string&kind,float parameter){using Q=std::priority_queue<std::pair<float,Node>,std::vector<std::pair<float,Node>>,Index::CompareByFirst>;Result r;Node cur=i.enterpoint_node_;float cd=dist(i,q,cur);std::size_t up=0;for(int l=i.maxlevel_;l>0;--l){bool change=true;while(change){change=false;for(auto v:upper(i,cur,l)){float d=dist(i,q,v);++up;if(d<cd){cd=d;cur=v;change=true;}}}}Q top,candidates;float entry=dist(i,q,cur),lower=entry;top.emplace(entry,cur);candidates.emplace(-entry,cur);std::vector<bool>seen(i.cur_element_count.load()),by_delta(seen.size());seen[cur]=true;std::size_t expanded=0;auto search_ef=std::max(k,ef);while(!candidates.empty()){auto item=candidates.top();float current_distance=-item.first;if(current_distance>lower)break;candidates.pop();Node u=item.second;if(by_delta[u]){++r.delta_expanded;if(r.first_delta_expansion<0)r.first_delta_expansion=expanded;}bool allow=kind=="union"||(kind=="scale"&&current_distance/scale[u]>parameter)||(kind=="depth"&&expanded<static_cast<std::size_t>(parameter));auto visit=[&](Node v,bool is_delta){if(seen[v])return;seen[v]=true;float d=dist(i,q,v);if(is_delta)++r.delta_calls;else ++r.original_calls;if(top.size()<search_ef||lower>d){candidates.emplace(-d,v);top.emplace(d,v);if(is_delta){by_delta[v]=true;++r.delta_enqueued;}if(top.size()>search_ef)top.pop();if(!top.empty())lower=top.top().first;}};for(auto v:o[u])visit(v,false);if(allow)for(auto v:delta[u])visit(v,true);++expanded;}while(top.size()>k)top.pop();std::priority_queue<std::pair<float,hnswlib::labeltype>>out;while(!top.empty()){out.emplace(top.top().first,i.getExternalLabel(top.top().second));top.pop();}r.labels=ordered(std::move(out));r.ndc=up+r.original_calls+r.delta_calls+2;return r;}
std::size_t hits(const Labeled&r,const Truth&t,std::size_t q){std::set<std::uint32_t>x;for(std::size_t i=0;i<t.k;++i)x.insert(t.x[q*t.k+i]);std::size_t h=0;for(auto&v:r)h+=x.count(v.second);return h;}
void emit(std::ofstream&f,const std::string&run,const std::string&mode,const Index&i,const Adj&o,const Adj&d,const std::vector<float>&s,const Matrix&q,const Truth&t,const std::vector<std::size_t>&grid,const std::string&kind,float p,bool native){for(auto ef:grid){if(native)const_cast<Index&>(i).setEf(ef);for(std::size_t n=0;n<q.rows;++n){auto*x=q.x.data()+n*q.cols;auto r=search(i,o,d,s,x,t.k,ef,kind,p);if(native&&ordered(i.searchKnn(x,t.k))!=r.labels)throw std::runtime_error("Original diagnostic search differs from native");f<<run<<','<<mode<<','<<ef<<','<<n<<','<<static_cast<double>(hits(r.labels,t,n))/t.k<<','<<r.ndc<<','<<r.original_calls<<','<<r.delta_calls<<','<<r.delta_enqueued<<','<<r.delta_expanded<<','<<r.first_delta_expansion<<'\n';}}}
}
int main(int argc,char**argv){try{if(argc!=11){std::cerr<<"usage: hnsw_sgdr_gate_o_search INDEX QUERIES TRUTH METRIC EFS RUN ORIGINAL_EDGES DELTA_EDGES OUTPUT META\n";return 2;}auto q=matrix(argv[2]);auto t=truth(argv[3]);if(q.rows!=500||t.rows!=500||t.k!=10)throw std::runtime_error("requires frozen 500x10 inputs");std::string metric=argv[4];Space space(q.cols,metric=="ip");Index index(&space,argv[1],false);auto o=edges(argv[7],10000),d=edges(argv[8],10000),s=scales(index,o),grid=efs(argv[5]);std::ofstream f(argv[9]);f<<"run_id,mode,ef_search,query_id,recall,ndc,original_calls,delta_calls,delta_enqueued,delta_expanded,first_delta_expansion\n";Adj empty(10000);emit(f,argv[6],"Original",index,o,empty,s,q,t,grid,"original",0,true);emit(f,argv[6],"Union-All",index,o,d,s,q,t,grid,"union",0,false);for(float x:{1.f,1.5f,2.f,3.f,4.f})emit(f,argv[6],"Scale-"+std::to_string(x),index,o,d,s,q,t,grid,"scale",x,false);for(float x:{4.f,8.f,16.f,32.f})emit(f,argv[6],"Depth-"+std::to_string(static_cast<int>(x)),index,o,d,s,q,t,grid,"depth",x,false);std::ofstream m(argv[10]);m<<"{\n  \"status\": \"complete\",\n  \"native_original_exact\": true,\n  \"diagnostic_only\": true,\n  \"validation_dev_accessed\": false,\n  \"formal_test_members_accessed\": false\n}\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
