#include "hnswlib/hnswlib.h"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <limits>
#include <queue>
#include <stdexcept>
#include <string>
#include <vector>
class CountingL2 final:public hnswlib::SpaceInterface<float>{struct S{size_t d;std::atomic<long>*c;};std::atomic<long> c_{0};S s_;static float f(const void*a,const void*b,const void*p){auto*s=(const S*)p;s->c->fetch_add(1);auto*x=(const float*)a,*y=(const float*)b;float z=0;for(size_t i=0;i<s->d;i++){float q=x[i]-y[i];z+=q*q;}return z;}public:CountingL2(size_t d):s_{d,&c_}{}size_t get_data_size()override{return s_.d*4;}hnswlib::DISTFUNC<float>get_dist_func()override{return f;}void*get_dist_func_param()override{return&s_;}void reset(){c_=0;}long count()const{return c_;}};
using Index=hnswlib::HierarchicalNSW<float>;using IQ=std::priority_queue<std::pair<float,hnswlib::tableint>,std::vector<std::pair<float,hnswlib::tableint>>,Index::CompareByFirst>;
struct CP{size_t q,checkpoint,queue,top,newvisited,ndc;double churn,kth_improve,gap;};struct R{std::vector<hnswlib::labeltype>labels;std::vector<hnswlib::tableint>order;std::vector<CP>cp;long ndc;};
static std::vector<hnswlib::tableint>nbr(const Index&i,hnswlib::tableint n,int l){auto*r=i.get_linklist_at_level(n,l);auto d=i.getListCount(r);auto*p=(hnswlib::tableint*)(r+1);return{p,p+d};}
static float dist(const Index&i,const void*q,hnswlib::tableint n){return i.fstdistfunc_(q,i.getDataByInternalId(n),i.dist_func_param_);}static std::vector<hnswlib::labeltype> labs(IQ q,const Index&i,size_t k){while(q.size()>k)q.pop();std::vector<hnswlib::labeltype>o;while(!q.empty()){o.push_back(i.getExternalLabel(q.top().second));q.pop();}std::sort(o.begin(),o.end());return o;}
static R spike(const Index&i,const void*q,size_t k,size_t ef,size_t qid,bool checkpoints,CountingL2&sp){R r;auto cur=i.enterpoint_node_;float cd=dist(i,q,cur);for(int l=i.maxlevel_;l>0;l--){bool ch=true;while(ch){ch=false;for(auto n:nbr(i,cur,l)){float d=dist(i,q,n);if(d<cd){cd=d;cur=n;ch=true;}}}}IQ top,cand;float ed=dist(i,q,cur),lb=ed;top.emplace(ed,cur);cand.emplace(-ed,cur);std::vector<uint8_t>vis(i.cur_element_count.load());vis[cur]=1;size_t visited=1,lastv=1,next=0;std::vector<size_t>marks{16,48,128};std::vector<hnswlib::labeltype>prev;float prevk=std::numeric_limits<float>::infinity();while(!cand.empty()){auto p=cand.top();float cdist=-p.first;if(cdist>lb)break;cand.pop();auto u=p.second;r.order.push_back(u);for(auto n:nbr(i,u,0)){if(vis[n])continue;vis[n]=1;visited++;float d=dist(i,q,n);if(top.size()<std::max(ef,k)||lb>d){cand.emplace(-d,n);top.emplace(d,n);if(top.size()>std::max(ef,k))top.pop();lb=top.top().first;}}if(checkpoints&&next<marks.size()&&r.order.size()>=marks[next]){auto now=labs(top,i,k);size_t common=0;for(auto a:now)if(std::find(prev.begin(),prev.end(),a)!=prev.end())common++;double churn=prev.empty()?1.0:1.0-double(common)/k;float kth=top.empty()?0:top.top().first;double imp=std::isfinite(prevk)&&prevk!=0?(prevk-kth)/std::max(std::abs(prevk),1e-12f):0;double gap=cand.empty()?0:(-cand.top().first-kth)/std::max(std::abs(kth),1e-12f);r.cp.push_back({qid,marks[next],cand.size(),top.size(),visited-lastv,(size_t)sp.count(),churn,imp,gap});prev=now;prevk=kth;lastv=visited;next++;}}
 r.labels=labs(top,i,k);r.ndc=sp.count();return r;}
static std::vector<float>readbin(const std::string&p,uint32_t&n,uint32_t&d){std::ifstream f(p,std::ios::binary);f.read((char*)&n,4);f.read((char*)&d,4);std::vector<float>x((size_t)n*d);f.read((char*)x.data(),x.size()*4);return x;}
int main(int ac,char**av){if(ac!=5){std::cerr<<"index queries trace equivalence\n";return 2;}uint32_t n,d;auto q=readbin(av[2],n,d);n=std::min<uint32_t>(n,500);CountingL2 sp(d);Index index(&sp,av[1],false,0);index.setEf(256);std::ofstream o(av[3]),eq(av[4]);o<<"query_id,checkpoint,topk_churn,kth_distance_improvement,frontier_kth_gap,candidate_queue_size,top_candidates_size,new_visited,ndc\n";eq<<"query_id,topk_equal,ndc_equal,visited_order_equal,checkpoint_read_only,fallback_reuses_state,native_ndc,spike_ndc\n";for(size_t z=0;z<n;z++){auto*p=q.data()+z*d;sp.reset();auto a=spike(index,p,10,256,z,false,sp);sp.reset();auto b=spike(index,p,10,256,z,true,sp);sp.reset();auto native=index.searchKnn(p,10);std::vector<hnswlib::labeltype>nl;while(!native.empty()){nl.push_back(native.top().second);native.pop();}std::sort(nl.begin(),nl.end());long nn=sp.count();if(a.labels!=b.labels||a.labels!=nl||a.ndc!=b.ndc||a.ndc!=nn||a.order!=b.order)throw std::runtime_error("prefix equivalence failure query "+std::to_string(z));eq<<z<<",1,1,1,1,1,"<<nn<<','<<a.ndc<<'\n';for(auto&c:b.cp)o<<c.q<<','<<c.checkpoint<<','<<c.churn<<','<<c.kth_improve<<','<<c.gap<<','<<c.queue<<','<<c.top<<','<<c.newvisited<<','<<c.ndc<<'\n';}std::cout<<"queries="<<n<<" equivalent=1 fallback_reuses_state=1 checkpoints=3\n";}
