import csv, hashlib, json, platform, subprocess
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

ROOT=Path('/home/wlk/projects/navigation-aware-resistance-hnsw-ocgt')
DER=ROOT/'results/index_conditionality/ocgt_v2/derived'; FIG=ROOT/'results/index_conditionality/ocgt_v2/figures'; DOC=ROOT/'docs/index_conditionality/ocgt_v2'; MAN=ROOT/'manifests/index_conditionality/ocgt_v2'
FIG.mkdir(parents=True,exist_ok=True);DOC.mkdir(parents=True,exist_ok=True)
summary=json.loads((DER/'full_summary.json').read_text())

datasets=['arxiv_nomic_10k','glove100_10k','sift_10k']; labels=['Arxiv','GloVe','SIFT']
vals=[100*summary['oracle_headroom_by_dataset'][d] for d in datasets]
plt.figure(figsize=(6,4));plt.bar(labels,vals,color=['#4C78A8','#F58518','#54A24B']);plt.ylabel('Oracle NDC headroom (%)');plt.tight_layout();plt.savefig(FIG/'oracle_headroom.png',dpi=180);plt.close()
ome=[summary['conditionality'][d]['omega'] for d in datasets];rho=[summary['conditionality'][d]['centered_spearman_median'] for d in datasets];jac=[summary['conditionality'][d]['hard_top10_jaccard_median'] for d in datasets]
x=np.arange(3);w=.25;plt.figure(figsize=(7,4));plt.bar(x-w,ome,w,label='Omega');plt.bar(x,rho,w,label='Centered Spearman');plt.bar(x+w,jac,w,label='Hard-10% Jaccard');plt.xticks(x,labels);plt.ylim(0,1);plt.legend();plt.tight_layout();plt.savefig(FIG/'conditionality_summary.png',dpi=180);plt.close()
pred=summary['predictors'];lid=[100*pred[d]['LID_STATIC']['ndc_gain'] for d in datasets];sheaf=[100*pred[d]['SHEAF']['ndc_gain'] for d in datasets];plt.figure(figsize=(7,4));plt.bar(x-w/2,lid,w,label='LID/static');plt.bar(x+w/2,sheaf,w,label='SHEAF actual probe cost');plt.axhline(0,color='black',lw=.8);plt.xticks(x,labels);plt.ylabel('NDC gain (%)');plt.legend();plt.tight_layout();plt.savefig(FIG/'predictor_actual_cost.png',dpi=180);plt.close()

theory='''# OCGT-v2 theory notes\n\n## Status taxonomy\n\nStatements below distinguish mathematical propositions, empirical observations, inferences, and open questions.\n\n## Proposition 1: query-only non-identifiability\n\nFor fixed data X and query q, two valid HNSW realizations G1 and G2 may require budgets a<b. Any predictor observing only phi(q,X) emits the same budget on both graphs. A budget below b can violate target recall on G2; a budget at least b over-spends by at least b/a on G1. This is an information limitation, not a claim that every dataset exhibits the gap.\n\n## Proposition 2: scalar calibration insufficiency\n\nIf two queries reverse their required-budget ordering between graphs, no strictly monotone scalar mapping can reproduce both target-graph budgets exactly. The proof follows immediately because a monotone map preserves order.\n\n## Proposition 3: realizable-gain upper bound\n\nRealized normalized gain is bounded above by oracle headroom minus normalized probe and prediction-error costs. The bound is bookkeeping: any observation cost and over-search consumes part of the oracle saving.\n\n## Proposition 4: finite-beam non-monotonicity\n\nAdding reachable edges cannot reduce graph-theoretic reachability, but may change finite candidate-queue ordering and evict a useful state. Thus finite-beam recall need not be monotone under edge addition or larger local branching. This does not imply that increasing ef is generally harmful; it establishes only that monotonicity needs proof for the exact search implementation.\n\n## Empirical observation\n\nThe 10K fixture shows large oracle headroom and substantial query-by-graph interaction, while probe-cost-aware predictors fail to realize it. Cross-order transfer is materially worse than same-order transfer.\n\n## Inference\n\nThe most plausible scientific scope is HNSW construction-history sensitivity, not a graph-agnostic query-difficulty law. This inference is descriptive because OCGT-v2 is invalid as a confirmatory experiment.\n\n## Open questions\n\nWhether the pattern persists at 100K/1M scale, across independent queries, and in other graph-ANNS families remains open.\n'''
(DOC/'theory.md').write_text(theory)
literature='''# Literature matrix\n\n| Work | Primary contribution | Relation to OCGT-v2 | Novelty implication |\n|---|---|---|---|\n| Malkov & Yashunin, *Efficient and robust approximate nearest neighbor search using HNSW* (https://arxiv.org/abs/1603.09320) | Defines hierarchical NSW construction and search | Establishes randomized hierarchy and incremental construction mechanisms | OCGT-v2 does not claim a new HNSW algorithm |\n| Aumüller & Ceccarello, *The Role of Local Intrinsic Dimensionality in Benchmarking NNS* (https://arxiv.org/abs/1907.07387) | Connects LID to query-set difficulty | Motivates the static LID baseline | Query difficulty itself is not novel; graph-instance conditionality is the narrower hypothesis |\n| He et al., *On the Difficulty of Nearest Neighbor Search* (https://arxiv.org/abs/1206.6411) | Introduces Relative Contrast as a difficulty measure | Motivates query-only geometry features | Static geometry baselines are prior art |\n| Zhang & Miller, *Distribution-Aware Exploration for Adaptive HNSW Search* (https://arxiv.org/abs/2512.06636) | Proposes adaptive per-query ef selection | Closest adaptive-search direction found | Any future algorithm claim must differentiate construction-history transfer and fully charge probe cost |\n| nmslib/hnswlib official implementation (https://github.com/nmslib/hnswlib) | Reference implementation and parameter semantics | Code base used by this project | Implementation behavior is not a new contribution |\n\n## Novelty assessment\n\nA defensible contribution would be a controlled measurement of how HNSW construction history changes per-query sufficient budgets and breaks cross-index transfer. The present run cannot establish that claim confirmatorily because its reproduction and raw-schema gates were not completed before performance collection.\n'''
(DOC/'literature_matrix.md').write_text(literature)

invalid_reasons=['OCGT-v2 Original reproduction Gate was not completed before the 27-graph matrix','raw query rows omit required entry_point, graph_checksum, candidate_checksum, and explicit query_split','exact query IDs and RNG algorithm were materialized only after performance collection','graph invariants required by preregistration were not fully captured before temporary indexes were deleted']
report=f'''# OCGT-v2 final report\n\n## Primary status\n\n`INVALID_OCGT_V2_REPRODUCTION_OR_DATA_FAILURE`\n\nThe 27 graphs and 162,000 query-by-ef rows completed without runtime failures and without validation-dev or formal-test access. However, the confirmatory protocol is invalid because mandatory pre-performance reproduction and evidence-schema requirements were not satisfied. No KEEP/SHRINK/STOP algorithm authorization may be issued from this run.\n\n## Descriptive results (non-authorizing)\n\n- Oracle NDC headroom: Arxiv {vals[0]:.2f}%, GloVe {vals[1]:.2f}%, SIFT {vals[2]:.2f}%.\n- Omega: Arxiv {ome[0]:.3f}, GloVe {ome[1]:.3f}, SIFT {ome[2]:.3f}.\n- Centered Spearman median: {rho[0]:.3f}, {rho[1]:.3f}, {rho[2]:.3f}.\n- Hard top-10% Jaccard median: {jac[0]:.3f}, {jac[1]:.3f}, {jac[2]:.3f}.\n- Median transfer eta: Arxiv {summary['transfer_eta_by_dataset'][datasets[0]]:.3f}, GloVe {summary['transfer_eta_by_dataset'][datasets[1]]:.3f}, SIFT {summary['transfer_eta_by_dataset'][datasets[2]]:.3f}.\n- LID/static mean NDC gain is negative on all datasets. SHEAF correlations are sometimes higher, but actual two-probe cost makes NDC gain strongly negative.\n\nThese diagnostics point toward `SHRINK_TO_HNSW_CONSTRUCTION_HISTORY` as a shadow hypothesis: same-order cross-seed rankings are much more stable than cross-order rankings, and cross-order Oracle transfer is poor. Because invalidity has highest priority, this is not the official decision.\n\n## Invalidity reasons\n\n'''+'\n'.join(f'- {x}' for x in invalid_reasons)+'''\n\n## Scope limits\n\nAll evidence comes from three 10K train-side fixtures and 500 previously used design-dev queries per dataset. It is neither formal testing nor evidence of 100K/1M or industrial performance. No validation-dev or formal-test member was accessed.\n'''
(DOC/'final_report.md').write_text(report)

decision={'schema_version':1,'protocol':'OCGT-v2','status':'INVALID_OCGT_V2_REPRODUCTION_OR_DATA_FAILURE','old_protocol_status':'INVALID_EXPERIMENT_REPRODUCTION_OR_DATA_FAILURE','valid_experiment':False,'datasets':datasets,'base_size':10000,'queries_per_dataset':500,'graphs_planned':27,'graphs_completed':27,'query_runs_planned':162000,'query_runs_completed':162000,'validation_dev_accessed':False,'formal_test_accessed':False,'adaptive_tuning_performed':False,'recall_target':0.9,'oracle_headroom_by_dataset':summary['oracle_headroom_by_dataset'],'omega_by_dataset':{d:summary['conditionality'][d]['omega'] for d in datasets},'centered_spearman_by_dataset':{d:summary['conditionality'][d]['centered_spearman_median'] for d in datasets},'hard_tail_jaccard_by_dataset':{d:summary['conditionality'][d]['hard_top10_jaccard_median'] for d in datasets},'oracle_transfer_eta':summary['transfer_eta_by_dataset'],'lid_summary':{d:summary['predictors'][d]['LID_STATIC'] for d in datasets},'sheaf_summary':{d:summary['predictors'][d]['SHEAF'] for d in datasets},'actual_probe_cost_included':True,'primary_gate_pass':False,'stop_reasons':invalid_reasons,'continue_reasons':[],'shadow_non_authorizing_hypothesis':'SHRINK_TO_HNSW_CONSTRUCTION_HISTORY','evidence_sha256':'manifests/index_conditionality/ocgt_v2/evidence_sha256.json'}
(MAN/'final_decision.json').write_text(json.dumps(decision,indent=2)+'\n')

files=[p for base in [DER,FIG,DOC,MAN] for p in base.rglob('*') if p.is_file()]
hashes={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(files)}
(MAN/'evidence_sha256.json').write_text(json.dumps(hashes,indent=2)+'\n')
(DOC/'environment.md').write_text(f'# Environment\n\n- Python: {platform.python_version()}\n- Platform: {platform.platform()}\n- Git base: 759e605044491bb911dc74a6839cedd89a200d1b\n- Analysis commit parent: {subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()}\n- Validation-dev accessed: false\n- Formal-test accessed: false\n')
print(json.dumps(decision,indent=2))
