#!/usr/bin/env python3
import csv,json,hashlib,time
from pathlib import Path
import matplotlib.pyplot as plt
ROOT=Path('/home/wlk/projects/navigation-aware-resistance-hnsw-rcrs');OUT=ROOT/'results/rcrs_fast';DOC=ROOT/'docs/rcrs_fast';FIG=ROOT/'figures/rcrs_fast';FIG.mkdir(parents=True,exist_ok=True)
absr=list(csv.DictReader(open(OUT/'absolute_regret.csv')));con=list(csv.DictReader(open(OUT/'implementation_contrast.csv')));gap=list(csv.DictReader(open(OUT/'monotone_gap.csv')))
ds=['arxiv_nomic_100k','glove100_100k','sift_100k'];h=[next(x for x in absr if x['index']=='hnswlib' and x['dataset']==d) for d in ds]
plt.figure(figsize=(7,4));x=range(3);v=[float(next(z for z in con if z['dataset']==d and z['contrast']=='hnswlib-faiss')['estimate']) for d in ds];lo=[float(next(z for z in con if z['dataset']==d and z['contrast']=='hnswlib-faiss')['ci_low']) for d in ds];hi=[float(next(z for z in con if z['dataset']==d and z['contrast']=='hnswlib-faiss')['ci_high']) for d in ds];plt.errorbar(x,v,yerr=[[a-b for a,b in zip(v,lo)],[a-b for a,b in zip(hi,v)]],fmt='o');plt.axhline(0,color='black',lw=.8);plt.xticks(x,ds,rotation=15);plt.title('hnswlib - Faiss history-effect contrast');plt.tight_layout();plt.savefig(FIG/'implementation_contrast.png',dpi=150);plt.savefig(FIG/'implementation_contrast.pdf');plt.close()
plt.figure(figsize=(7,4));x=range(3);w=.25;plt.bar([i-w for i in x],[float(z['optimal_monotone_tax']) for z in gap],w,label='safe monotone');plt.bar(x,[float(z['global_conformal_cost_fraction']) for z in gap],w,label='Global');plt.bar([i+w for i in x],[float(z['gcc_cost_fraction']) for z in gap],w,label='GCC');plt.axhline(0,color='black',lw=.8);plt.xticks(x,ds,rotation=15);plt.legend();plt.title('Safe monotone tax versus prior risk-tolerant lanes');plt.tight_layout();plt.savefig(FIG/'monotone_gap.png',dpi=150);plt.savefig(FIG/'monotone_gap.pdf');plt.close()
tax={z['dataset']:float(z['mean_exact_monotone_tax']) for z in h};contrast={d:float(next(z for z in con if z['dataset']==d and z['contrast']=='hnswlib-faiss')['estimate']) for d in ds}
(DOC/'resumability_spike.md').write_text('''# hnswlib resumability spike\n\nA frozen SIFT-100K Original index and 500 previously used train-side Cross-Index queries were evaluated at fixed `ef=256`. The spike allocates the full fixed-search candidate/result capacity from the start and inserts three read-only checkpoints after 16, 48 and 128 base expansions. It never performs a smaller independent search.\n\nFor all 500 queries, checkpoint-enabled and checkpoint-disabled spike paths had identical top-k labels, exact distance counts and visited expansion order; both were also exactly equal to native `searchKnn` top-k and exact distance counts. The checkpoint callback only reads heaps/counters. Continuing after a checkpoint uses the same candidate queue, result heap and visited set, so fixed fallback does not restart or repeat distance computations. The 1,500 aggregate checkpoint rows contain churn, kth-distance improvement, frontier gap, queue sizes, newly visited count and NDC; no node trace or queue snapshot is stored.\n\nThis establishes an implementation path for a feature-flagged RCRS prototype, not an early-stop safety or performance result. No stopping model or threshold was trained.\n''')
decision={'schema_version':1,'status':'FAST_FEASIBILITY_FINAL','decision':'CONTINUE_RCRS_FULL_IMPLEMENTATION','monotone_lower_bound_proved':True,'hnswlib_monotone_tax':tax,'global_gcc_gap_interpretation':'PRIOR_LANES_ARE_RISK_TOLERANT_NONDEPLOYABLE_AND_USE_DISTINCT_QUERY_SPLITS; THEY_CAN_FALL_BELOW_THE_POINTWISE_SAFE_MONOTONE_COST','hnswlib_faiss_contrast':contrast,'prefix_queries':500,'prefix_equivalence':True,'fallback_reuses_state':True,'checkpoint_additional_ndc':0,'trace_pilot_complete':True,'rcrs_complete':False,'online_oracle_used':False,'bootstrap':1000,'bootstrap_seed':991,'evidence':'EXPLORATORY_FAST_BOOTSTRAP','validation_dev_accessed':False,'formal_test_accessed':False}
(ROOT/'manifests/rcrs_fast_decision.json').write_text(json.dumps(decision,indent=2)+'\n')
(DOC/'final_report.md').write_text(f'''# RCRS Fast Feasibility Sprint final report\n\nFinal label: **CONTINUE_RCRS_FULL_IMPLEMENTATION**. The discrete safe monotone-majorant theorem and inversion matching lower bound passed eight synthetic tests. Mean exact hnswlib monotone NDC taxes relative to fixed cost were Arxiv {tax['arxiv_nomic_100k']:.4f}, GloVe {tax['glove100_100k']:.4f}, and SIFT {tax['sift_100k']:.4f}; all 3/3 are positive and nontrivial. Direct hnswlib-minus-Faiss cross-minus-same contrasts were Arxiv {contrast['arxiv_nomic_100k']:.4f}, GloVe {contrast['glove100_100k']:.4f}, and SIFT {contrast['sift_100k']:.4f}, with 1,000-query exploratory bootstrap intervals in `implementation_contrast.csv`.\n\nGlobal/GCC appear cheaper than the pointwise-safe monotone optimum because they are risk-tolerant, non-deployable source-Oracle lanes evaluated on a distinct prior split; the comparison is descriptive and is not evidence that they dominate a safe monotone policy. The gap demonstrates why raw inversion rate and candidate cost alone cannot replace a common safety constraint.\n\nThe 500-query prefix spike passed exact top-k, NDC and visited-order equivalence, reuses fallback state and adds no distance calls. This authorizes a later full RCRS implementation study, but this sprint did not implement or validate an early-stopping controller and does not authorize validation-dev, formal-test, or a three-dataset RCRS matrix.\n''')
files=[p for p in list(OUT.glob('*'))+list(DOC.glob('*'))+list(FIG.glob('*'))+[ROOT/'manifests/rcrs_fast_decision.json'] if p.is_file() and p.name not in ('checksums.sha256','finalize.out') and not p.name.endswith('.f32bin')]
with open(OUT/'checksums.sha256','w') as f:
 for p in sorted(files):f.write(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+str(p.relative_to(ROOT))+'\n')
print(json.dumps(decision,indent=2))
