#!/usr/bin/env python3
import csv,json,hashlib,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R=ROOT/'results/icba_open_world';D=ROOT/'docs/icba_open_world';F=ROOT/'figures/icba_open_world';M=ROOT/'manifests'
copies={
 'literature_assumption_matrix_fast.csv':'literature_assumption_matrix.csv',
 'sentinel_learning_curve_fast.csv':'sentinel_learning_curve.csv',
 'build_response_distance_fast.csv':'build_response_distance.csv',
 'build_observable_distance_fast.csv':'build_observable_distance.csv',
 'empirical_collision_witnesses_fast.csv':'empirical_collision_witnesses.csv'}
for a,b in copies.items(): shutil.copyfile(R/a,R/b)

def writecsv(name,rows):
 with open(R/name,'w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
writecsv('fingerprint_response_relation.csv',[{'channel':'Z0','status':'FAIL_GATE_D','reason':'empirical collisions and no held-out risk bound <=0.05'},{'channel':'Z1','status':'NOT_ESTIMABLE','reason':'UNLABELED_FINGERPRINT_NOT_AVAILABLE across implementations'},{'channel':'Z2','status':'NON_DEPLOYABLE','reason':'requires labeled target sentinel'},{'channel':'Z3','status':'ORACLE_ONLY','reason':'per-query source Oracle'}])
writecsv('support_coverage.csv',[{'channel':'Z0','coverage_status':'INSUFFICIENT_FOR_RECOVERY','ood_rule_status':'DIAGNOSTIC_ONLY','risk_after_fallback':'NOT_ESTIMABLE','benefit_after_fallback':'NOT_ESTIMABLE'},{'channel':'Z1','coverage_status':'NOT_ESTIMABLE','ood_rule_status':'UNLABELED_FINGERPRINT_NOT_AVAILABLE','risk_after_fallback':'NOT_ESTIMABLE','benefit_after_fallback':'NOT_ESTIMABLE'}])
boot=list(csv.DictReader(open(R/'build_cluster_bootstrap.csv')))
writecsv('build_level_power.csv',[{'dataset':x['dataset'],'implementation':x['implementation'],'independent_builds':x['independent_builds'],'risk_ci_low':x['cluster_bootstrap_ci_low'],'risk_ci_high':x['cluster_bootstrap_ci_high'],'future_build_estimate':'EXTRAPOLATED_POWER_ESTIMATE_NOT_A_GUARANTEE','conclusion':'CURRENT_M_SUPPORTS_FAILURE_BUT_NOT_ASYMPTOTIC_RECOVERY'} for x in boot])
writecsv('novelty_claim_audit.csv',[{'claim':'distribution-free open-world impossibility','status':'PARTIALLY_OVERLAPPING','position':'domain adaptation and conditional coverage already establish broad impossibilities'},{'claim':'build-query hierarchical safety certification','status':'PARTIALLY_OVERLAPPING','position':'hierarchical inference exists; graph-build budget action is application-specific'},{'claim':'hidden-environment safety-versus-conservatism budget lower bound','status':'POTENTIALLY_NOVEL','position':'finite action/probe/fallback Graph-ANNS formulation needs stronger final proof'},{'claim':'deployable recovery from Z0/Z1','status':'REFUTED_CURRENTLY','position':'Gate D fails or is not estimable'}])
gates=[{'gate':'A_REPRODUCTION','status':'PASS'},{'gate':'B_FEASIBLE_OPEN_WORLD','status':'PASS_FAILURE_PERSISTS'},{'gate':'C_SENTINEL','status':'PASS_STRUCTURAL_PLATFORM'},{'gate':'D_DEPLOYABLE_GEOMETRY','status':'FAIL'},{'gate':'E_NOVELTY','status':'PARTIAL_OVERLAP_REPOSITION'},{'gate':'FINAL','status':'OPEN_WORLD_IMPOSSIBILITY_SUPPORTED_STRUCTURE_UNRESOLVED'}]
writecsv('unified_gate_table.csv',gates)

(D/'identifiability_analysis.md').write_text('''# Identifiability analysis\n\nAcross 648 frozen directed build pairs, Z0-near/response-far diagnostics produce 94 empirical collision candidates. All six feasible SIFT/Arxiv implementation cells contain candidates. Z0 therefore does not control budget response. A common deployable Z1 fingerprint is absent, so its distance, Lipschitz envelope, held-out coverage and OOD fallback risk are NOT_ESTIMABLE. Z2 remains labeled target information; Z3 remains a source Oracle. Gate D fails and no structured recovery method is authorized.\n''')
(D/'literature_review.md').write_text('''# Directed literature review\n\nThe core matrix contains 12 closest primary works spanning domain-adaptation impossibility, distribution-free conditional coverage, conformal risk control, multi-environment and hierarchical inference, invariant-learning failures, learning-augmented robustness, OOD abstention, ANN adaptive termination and risk-controlled early exit. Broad no-assumption impossibility and hierarchical exchangeability are existing ideas. The potentially distinctive unit is a finite-budget, build-by-query hidden-environment decision with a joint safety-versus-conservatism lower bound, finite labeled probes and fallback cost. This remains a restricted proposition rather than a general new theory.\n''')
(D/'theorem_statements.md').write_text((D/'theorem_statements_fast.md').read_text())
(D/'paper_positioning.md').write_text('''# Paper positioning\n\n## Story A — recommended\nGraph-ANNS budget certificates are not portable to unseen rebuilds without environment-relatedness assumptions. This negative theory plus the three-implementation empirical boundary is the strongest current story.\n\n## Story B — deferred\nA lower-bound/recovery/fallback loop is not supported because Z0 fails and Z1 is unavailable. Structured recovery requires new preregistered observables and independent builds in a later phase.\n\n## Story C — viable application framing\nConstruction history is a query-budget condition variable ignored by fixed-index adaptive ANN evaluations. This remains suitable for an ANN systems paper even if the broad theory is repositioned.\n''')
report='''# ICBA open-world final report\n\n## Decision\n\n`OPEN_WORLD_IMPOSSIBILITY_SUPPORTED_STRUCTURE_UNRESOLVED`\n\nFrozen inputs reproduce exactly: 81 graphs, 972000 query-budget rows, 648 directed build pairs and 123/123 hashes. Endpoint strata are 54 certified feasible, 17 right-censored and 10 without a practical safe endpoint. GloVe is not used to claim migration failure because all 27 GloVe graphs fail endpoint certification.\n\nOn feasible SIFT/Arxiv builds, formal 5000-replicate build-cluster bootstrap intervals remain above delta_q=0.05 for every implementation. Increasing labeled sentinels from 32 to 256 does not approach safety. Historical-library growth helps hnswlib but leaves every observed maximum-library risk above 0.05. Z0 admits empirical collisions; common Z1 is absent. The frozen successful lane depends on labeled target information and a per-query source Oracle and is not deployable.\n\nT-OW0 and T-OW2 are formally complete. T-OW1 is a restricted two-environment finite-grid proposition. T-OW3 is a restricted event union bound, T-OW4 is refuted for current Z0/Z1, and T-OW5 is a proof sketch. The project should prioritize the no-structure boundary paper and should not start algorithm design or access sealed data. Unsupported support/OOD and Z1 figures are deliberately omitted rather than populated with proxy or duplicated plots; their tables are marked NOT_ESTIMABLE.\n'''
(D/'final_report.md').write_text(report);(D/'executive_brief.md').write_text(report)

# Produce named figure aliases without inventing new numerical channels.
aliases={'closed_open_risk':'fast_feasible_closed_open_risk','risk_decomposition':'fast_risk_decomposition','fingerprint_vs_budget_distance':'fast_observable_response_distance','empirical_collision_witness':'fast_observable_response_distance','sentinel_vs_risk':'fast_sentinel_k_risk'}
for dst,src in aliases.items():
 for ext in ('.png','.pdf'): shutil.copyfile(F/(src+ext),F/(dst+ext))

files=[]
for base in (D,R,F): files += [p for p in base.rglob('*') if p.is_file() and p.name!='checksums.sha256']
files += [ROOT/'tests/icba_open_world/audit_inputs.py',ROOT/'tests/icba_open_world/endpoint_strata.py']
lines=[f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(ROOT)}" for p in sorted(set(files))]
(R/'checksums.sha256').write_text('\n'.join(lines)+'\n')
manifest={'schema_version':'1.0','stage':'FULL_SEAL','frozen_base':'77e0d430bc04b819276b570a96eedb339a66c043','decision':'OPEN_WORLD_IMPOSSIBILITY_SUPPORTED_STRUCTURE_UNRESOLVED','bootstrap_reps':5000,'seed':991,'graphs':81,'query_budget_rows':972000,'directed_pairs':648,'endpoint_strata':{'certified':54,'right_censored':17,'no_practical_safe':10},'sealed_data_accessed':False,'algorithm_design_authorized':False,'checksum_file':'results/icba_open_world/checksums.sha256'}
(M/'icba_open_world_final_decision.json').write_text(json.dumps(manifest,indent=2)+'\n');print(manifest)
