from pathlib import Path
import hashlib,json
import numpy as np
import pandas as pd

ROOT=Path('/home/wlk/projects/navigation-aware-resistance-hnsw'); OUT=ROOT/'results/icba_shared_cost_gate'; DOC=ROOT/'docs/icba_shared_cost_gate'; OUT.mkdir(parents=True,exist_ok=True); DOC.mkdir(parents=True,exist_ok=True)
use=['dataset','build','raw_ef','query_id','mask','base_hits','union_hits','base_risk','union_risk','primary_ndc','aux_ndc_sum','total_ndc','candidate_count']
d=pd.read_csv(ROOT/'results/icba_cals_seal/subset_results.csv.gz',usecols=use); d['recall']=d.base_hits/10
base=d[d['mask'].eq(0)].copy(); targets=pd.read_csv(ROOT/'results/icba_cals_seal/selection_actions.csv'); targets=targets[targets.action_scope.eq('TARGET_SPECIFIC_SELECTED_FIXED_SET')&targets.raw_ef.isin([8,16,32])]
rows=[]; critical=[]; overlap=[]; boot=[]
for _,a in targets.iterrows():
  e=int(a.raw_ef); en=min(64,2*e); p=d[(d.dataset.eq(a.dataset))&(d.build.eq(a.build))&(d.raw_ef.eq(e))&(d['mask'].eq(a['mask']))].copy(); n=base[(base.dataset.eq(a.dataset))&(base.build.eq(a.build))&(base.raw_ef.eq(en))][['query_id','total_ndc','base_hits','base_risk']].rename(columns={'total_ndc':'native_cost','base_hits':'native_hits','base_risk':'native_risk'}); b=base[(base.dataset.eq(a.dataset))&(base.build.eq(a.build))&(base.raw_ef.eq(e))][['query_id','total_ndc','base_hits','base_risk']].rename(columns={'total_ndc':'primary_cost','base_hits':'primary_hits','base_risk':'primary_risk'}); p=p.merge(b,on='query_id').merge(n,on='query_id'); p['d_cost_native']=p.native_cost-p.primary_cost; p['kappa_cost']=(p.native_cost-p.primary_cost)/p.aux_ndc_sum.replace(0,np.nan); p['recall_gain']=(p.union_hits-p.base_hits)/10; p['native_recall_gain']=(p.native_hits-p.base_hits)/10; p['risk_gain']=p.base_risk-p.union_risk; p['native_risk_gain']=p.base_risk-p.native_risk; p['kappa_recall']=(p.recall_gain*p.d_cost_native)/(p.native_recall_gain*p.aux_ndc_sum).replace(0,np.nan); p['kappa_hit']=(p.union_hits-p.base_hits)*p.d_cost_native/((p.native_hits-p.base_hits)*p.aux_ndc_sum).replace(0,np.nan); p['kappa_practical']=(p.risk_gain*p.d_cost_native)/(p.native_risk_gain*p.aux_ndc_sum).replace(0,np.nan); p['kappa_strong']=p.kappa_practical; p['candidate_kappa_lb']=p.candidate_count/p.aux_ndc_sum.replace(0,np.nan); p['quality_practical']=p.union_risk<p.primary_risk; p['quality_strong']=(p.union_hits/10>=.99)&(p.base_hits/10<.99); p['quality_route_b']=p.quality_practical; p['quality_route_a']=(p.union_risk<=p.native_risk+.005)&((p.union_hits-p.native_hits)/10>=-.001); p['quality_feasible']=p.quality_route_a|p.quality_route_b
  q=p[['dataset','build','raw_ef','query_id','quality_practical','quality_strong','quality_route_a','quality_route_b','quality_feasible','primary_risk','union_risk','native_risk','primary_hits','union_hits','native_hits','primary_cost','aux_ndc_sum','native_cost','candidate_count','kappa_cost','kappa_recall','kappa_hit','kappa_practical','kappa_strong','candidate_kappa_lb']]; rows.append(q)
  feasible=q[q.quality_feasible]
  for metric in ['kappa_cost','kappa_recall','kappa_hit','kappa_practical','kappa_strong']:
    v=feasible[metric].replace([np.inf,-np.inf],np.nan).dropna().to_numpy(); v=v[v>0]; rng=np.random.default_rng(991); bm=np.array([rng.choice(v,len(v),replace=True).mean() for _ in range(5000)]) if len(v) else np.array([np.nan]); critical.append({'dataset':a.dataset,'build':a.build,'raw_ef':e,'portal_rule_ids':a.portal_rule_ids,'metric':metric,'quality_feasible_n':len(feasible),'n_positive':len(v),'mean':float(v.mean()) if len(v) else np.nan,'median':float(np.median(v)) if len(v) else np.nan,'p25':float(np.percentile(v,25)) if len(v) else np.nan,'p75':float(np.percentile(v,75)) if len(v) else np.nan,'ci_low':float(np.nanpercentile(bm,2.5)),'ci_high':float(np.nanpercentile(bm,97.5)),'required_compression':float(1-np.median(v)) if len(v) else np.nan,'top1pct_median':float(np.mean(np.sort(v)[:-max(1,int(np.ceil(len(v)*.01)))])) if len(v)>1 else (float(v.mean()) if len(v) else np.nan)})
  overlap.append({'dataset':a.dataset,'build':a.build,'raw_ef':e,'portal_rule_ids':a.portal_rule_ids,'candidate_union_cost_lower_bound_mean':float((p.primary_cost+p.candidate_count).mean()),'independent_aux_cost_mean':float(p.aux_ndc_sum.mean()),'candidate_kappa_lb_median':float(p.candidate_kappa_lb.median()),'semantics':'CANDIDATE_SET_COST_LOWER_BOUND; not visited/NDC overlap; shared wall-clock NOT_ESTIMABLE'})
  boot.append({'dataset':a.dataset,'build':a.build,'raw_ef':e,'quality_feasible_fraction':float(p.quality_feasible.mean()),'practical_risk_primary':float(p.primary_risk.mean()),'practical_risk_portal':float(p.union_risk.mean()),'strong_risk_primary':float((p.primary_hits<10).mean()),'strong_risk_portal':float((p.union_hits<10).mean()),'mean_recall_primary':float(p.primary_hits.mean()/10),'mean_recall_portal':float(p.union_hits.mean()/10)})
allq=pd.concat(rows,ignore_index=True); allq.to_csv(OUT/'quality_feasibility.csv',index=False); pd.DataFrame(critical).to_csv(OUT/'critical_compression.csv',index=False); pd.DataFrame(overlap).to_csv(OUT/'candidate_overlap_bounds.csv',index=False); pd.DataFrame(boot).to_csv(OUT/'bootstrap_results.csv',index=False)
cc=pd.DataFrame(critical); lb=pd.DataFrame(overlap); cm=cc[cc.metric.eq('kappa_cost')].merge(lb[['dataset','build','raw_ef','candidate_kappa_lb_median']],on=['dataset','build','raw_ef'],how='left'); cm['compression_margin']=cm['median']-cm.candidate_kappa_lb_median; cm['bound_semantics']='NON_DEPLOYABLE_LOWER_BOUND'; cm.to_csv(OUT/'compression_margin.csv',index=False)
# Build-cluster and LOBO summaries are descriptive because there are only three named builds.
l=[]
for (ds,e),g in allq.groupby(['dataset','raw_ef']):
  for held in sorted(g.build.unique()):
    t=g[g.build.ne(held)]; h=g[g.build.eq(held)]; l.append({'dataset':ds,'heldout_build':held,'raw_ef':int(e),'train_mean_kappa_cost':float(t.kappa_cost.replace([np.inf,-np.inf],np.nan).median()),'heldout_median_kappa_cost':float(h.kappa_cost.replace([np.inf,-np.inf],np.nan).median()),'heldout_quality_fraction':float(h.quality_feasible.mean()),'heldout_positive_cost_space':bool((h.kappa_cost>0).mean()>0.5)})
pd.DataFrame(l).to_csv(OUT/'lobo_results.csv',index=False)
gate=pd.DataFrame([{'gate':'quality_candidates_present_both_datasets','passed':bool(allq.groupby('dataset').quality_feasible.mean().gt(0).all())},{'gate':'two_of_three_builds_positive_space','passed':bool((allq.groupby(['dataset','build']).kappa_cost.apply(lambda x:(x>0).mean()>0.5).groupby(level=0).sum()>=2).all())},{'gate':'top1pct_positive_space','passed':bool((cc[cc.metric.eq('kappa_cost')].top1pct_median>0).any())},{'gate':'candidate_union_margin_ge_010','passed':bool((cm.compression_margin>=.10).any())},{'gate':'required_compression_le_050','passed':bool((cc.required_compression<=.50).any())},{'gate':'shared_real_cost_estimable','passed':False}]); gate.to_csv(OUT/'unified_gate_table.csv',index=False)
decision='SHARED_COST_COMPRESSION_PLAUSIBLE_AUTHORIZE_MICROBENCHMARK' if bool(gate[gate.gate.ne('shared_real_cost_estimable')].passed.all()) else ('SHARED_COST_ONLY_ORACLE_BOUND_NO_IMPLEMENTATION' if bool(gate.iloc[0].passed) and bool(cm.compression_margin.ge(.10).any()) else 'SHARED_COST_COMPRESSION_INSUFFICIENT_CLOSE_PORTAL_METHOD_ROUTE')
(ROOT/'manifests/icba_shared_cost_gate_decision.json').write_text(json.dumps({'decision':decision,'frozen_parent':'e2e5a5d86042b76220199582e152c1391d52a794','evidence_levels':['COST_REALIZABILITY_AUDIT','EXPLORATORY_DEVELOPMENT','NON_DEPLOYABLE_LOWER_BOUND'],'microbenchmark_authorized':decision.startswith('SHARED_COST_COMPRESSION_PLAUSIBLE'),'shared_cost':'NOT_ESTIMABLE','sealed_roles_accessed':False},indent=2)+'\n'); print(decision); print(gate.to_string(index=False))
