import json
from pathlib import Path
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
R=Path('results/icba_ordered_rung_semantic_reaudit'); D=Path('docs/icba_ordered_rung_semantic_reaudit'); F=Path('figures/icba_ordered_rung_semantic_reaudit'); T=Path('tests/icba_ordered_rung_semantic_reaudit'); M=Path('manifests'); F.mkdir(parents=True,exist_ok=True)
for name in ['actual_budget_rung','ndc_cost_diagnostic','stable_event_nesting','raw_event_nesting','evaluation_uncertainty','cert_acceptance_error','safety_margin_acceptance','fallback_cost_waterfall','mean_p95_frontier','target_build_robustness','unified_gate']:
 fig,ax=plt.subplots(figsize=(5.5,3.5)); ax.text(.5,.5,'NOT_ESTIMABLE / semantic audit',ha='center',va='center'); ax.set_title(name.replace('_',' ')); ax.set_axis_off(); fig.tight_layout(); fig.savefig(F/(name+'.png'),dpi=120); fig.savefig(F/(name+'.pdf')); plt.close(fig)
manifest={'decision':'EXISTING_STAGE_FAMILY_NOT_ORDERED_BUT_THEORY_UNREFUTED','frozen_input':'83c7171f04b622088e39dc3fd9ea850437ae5fdc','evidence_level':'FIXED_TARGET_EXPLORATORY_DESIGN','actual_budget_action':'NOT_ESTIMABLE','deployable_base_policy':'DEPLOYABLE_BASE_POLICY_MISSING','stable_event_nesting':'NOT_ESTIMABLE','raw_event_nesting':'NOT_ESTIMABLE','method_implementation_authorized':False,'stable_by_construction_pivot':False,'validation_dev_accessed':False,'formal_test_accessed':False,'gloVe_accessed':False,'legacy':'LEGACY_BASELINE_CONDITIONAL_REPRODUCTION_111_OF_123'}
(M/'icba_ordered_rung_semantic_reaudit_decision.json').write_text(json.dumps(manifest,indent=2)+'\n')
(T/'test_ordered_reaudit.py').write_text('''import json\nfrom pathlib import Path\nimport pandas as pd,pytest\nR=Path("results/icba_ordered_rung_semantic_reaudit")\n@pytest.mark.parametrize("n",["rung_actions.csv","budget_action_monotonicity.csv","ndc_cost_monotonicity_diagnostic.csv","stable_budget_labels.csv","event_nesting_audit.csv","rejection_quadrants_corrected.csv","certificate_error_diagnostic.csv","sample_size_curves.csv","safety_margin.csv","fallback_cost_attribution.csv","tail_metrics.csv","fallback_frontier.csv","theory_contact_matrix_corrected.csv","unified_gate_table.csv"])\ndef test_outputs(n): assert (R/n).exists()\n@pytest.mark.parametrize("ds",["sift_100k","arxiv_nomic_100k"])\ndef test_dataset(ds): assert ds in set(pd.read_csv(R/"rejection_quadrants_corrected.csv").dataset)\ndef test_no_ndc_budget(): assert "NDC is not budget action" in Path("docs/icba_ordered_rung_semantic_reaudit/semantic_correction_note.md").read_text()\ndef test_not_estimable_budget(): assert pd.read_csv(R/"budget_action_monotonicity.csv").budget_action_monotone.eq("NOT_ESTIMABLE").all()\ndef test_cp_event(): assert pd.read_csv(R/"rejection_quadrants_corrected.csv").eval_state.notna().all()\ndef test_no_oracle(): assert not json.loads(Path("manifests/icba_ordered_rung_semantic_reaudit_decision.json").read_text())["method_implementation_authorized"]\ndef test_legacy(): assert "111_OF_123" in Path("docs/icba_ordered_rung_semantic_reaudit/limitations.md").read_text()\ndef test_no_sealed():\n x=json.loads(Path("manifests/icba_ordered_rung_semantic_reaudit_decision.json").read_text()); assert not x["validation_dev_accessed"] and not x["formal_test_accessed"] and not x["gloVe_accessed"]\ndef test_decision(): assert json.loads(Path("manifests/icba_ordered_rung_semantic_reaudit_decision.json").read_text())["decision"].startswith("EXISTING_STAGE_FAMILY")\n''')
print('sealed')
